name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "*/5 * * * *"
env:
  Token1: {{ secrets.BOT_TOKEN1 }}
  Token2: {{ secrets.BOT_TOKEN2 }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Permission
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: messge
      run : |
             Url=${{ env.Token1 }}\${{ env.Token2 }}
             curl -X POST -H 'Content-Type: application/json' -d '{"chat_id":"1081797517","text":"'"$(./out)"'", "disable_notification": true}' "https://api.telegram.org/bot\$Url\/sendMessage"

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "mehrelease"
        release_name: 'HEHE'
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out
        asset_name: binfile
        asset_content_type: application/octet-stream

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
