name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Permission
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: upload
      run:  |
        echo "::set-output name=outdated::$(./out)"
    - name: messge
      run : |
       curl -X POST -H 'Content-Type: application/json'-d '{"chat_id":"1081797517","text":"This is a test from curl", "disable_notification": true}' https://api.telegram.org/bot5160514641:AAFg-GXL_gNg1CHO33W9G1hTosiSvYkL4xg/sendMessage



