name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Permission
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: messge
      run : |
       curl -X POST -H 'Content-Type: application/json' -d '{"chat_id":"1081797517","text":"'"$(./out)"'", "disable_notification": true}' "https://api.telegram.org/bot5160514641:AAFg-GXL_gNg1CHO33W9G1hTosiSvYkL4xg/sendMessage"
