name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Permission
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: upload
      run:  |
        echo "::set-output name=outdated::$(./out)"


